### ISSUE TITLE
[Feat] 전략 상세페이지 조회 기능 구현

### ISSUE THREAD

**Issue by 5jeong** [FC-DEV-FinalProject/FinalProject_team3_BE#15]
## 어떤 기능인가요?

> 전략 상세페이지 조회 기능
## 작업 상세 내용

- [x] 전략 상세조회 #14 
- [x] 전략 분석그래프 데이터 조회(검색) #16 
- [x] 통계 데이터 조회 #19 
- [ ] 실계좌 이미지 목록 조회 #37
